### ISSUE TITLE
Google Summer of Code Ideas

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#1575]
- Implement quick start wizard for new users
- Work on any open issue
- Improve testing to cover major Borg versions
- Improve test coverage in general
- Work on Borg itself

**Comment by m3nu** [comment]
@sten0 , is Debian doing GSoC this year? Does it make sense to add Borg or Vorta via them? Since my company applies for the first time and I'm not sure it will be accepted. We're also not directly related to Borg, but could make sense via Debian. We'd need to talk to Thomas about suitable tasks for contributors. But I'm sure he could use the help for v2.

**Comment by m3nu** [comment]
@ThomasWaldmann, would you be open to having GSoC contributors work on Borg? Or know anyone from an umbrella organization that's applying? I could mentor them. @real-yfprojects and @witten maybe too. You could even apply as Waldmann EDV to increase our odds of getting accepted with some project.

**Comment by ThomasWaldmann** [comment]
@m3nu I'm ok with that, but I don't want to mentor or administrate personally, but rather work on borg2.

**Comment by m3nu** [comment]
No problem. I'll mentor. Already did it in 2018. Will see to get some spots for contributors first.

**Comment by witten** [comment]
I'd certainly be open to it if anyone's interested.

**Comment by m3nu** [comment]
Great! First step is to haven an org that's accepted. I applied with my company, but there are also umbrella orgs that get more contributor spots.

After that interested contributors (mostly CS students) apply to projects and get paid a small stipend by Google to work on a FOSS project. Mentors get a t-shirt. 😄

**Comment by real-yfprojects** [comment]
There is a [mentor guide](https://google.github.io/gsocguides/mentor/) from google. I can mentor one contributor. They guide states that we should request one slot per 2 mentors.

> Since my company applies for the first time and I'm not sure it will be accepted. 

A elaborated and well prepared application will be key to that. I think we should discuss the contents here.

#### more ideas

- implement exclude GUI
- improve modularization
- improve GUI (profile sidebar, file search in diff view, summary footer in source view, ... i have an extended list on my machine)
- error handling and report dialog/wizard

**Comment by m3nu** [comment]
They didn't ask for too much. I linked to this thread for ideas.

I'll invite you as mentor. Just share me the email to hello@borgbase.com

**Comment by ThomasWaldmann** [comment]
@m3nu Umbrella org could be Python (PSF) maybe.

**Comment by m3nu** [comment]
> @m3nu Umbrella org could be Python (PSF) maybe.

Excellent idea! Already emailed them to apply as PSF sub-org: https://python-gsoc.org/mentors.html#sub-orgs

**Comment by m3nu** [comment]
All applications are out. Applied directly as BorgBase, and with [PSF](https://blogs.python-gsoc.org/en/suborg/application/update/59/) (not public yet) and [Debian](https://wiki.debian.org/SummerOfCode2023/PendingProjects/BorgCollective) as sub-org.

From what I understand, Google will pay a stipend to both students (also called contributors or interns) and mentors that are accepted. If we join under Python (PSF) or Debian they will use the mentor stipend for their work (which is great!). If BorgBase gets accepted, I'd pass it to the Borg project somehow. In any case, it's better to have more mentors. So if there are regular contributors to the Borg or Borgmatic projects, we should reach out to them too. We could also reach out on Reddit, since there are close to 1000 members there that would possibly see a post.

Open questions and tasks:

- Do you have an email to use when inviting your as org admin/mentor, @real-yfprojects ?
- Would you want to be a mentor as well, @Hofer-Julian? Given your previous work. And to have more mentors.
- Would you want to be added as admin @ThomasWaldmann . There shouldn't be much time involved with this role and you can see some admin stuff. Signing up as backup mentor would be even better.
- Any regular contributor you on Borgmatic and Borg that may want to be mentors?

We also need good project management, since students will work remotely. I like the Kanban boards Thomas already uses ([e.g.](https://github.com/borgbackup/borg/projects/6)) and we should let them write weekly microblog-style updates (as the PSF does). I'd make sure this is all set up properly and students know what to work on.

**Comment by Hofer-Julian** [comment]
I can co-mentor, especially if the money goes to PSF or borg. However, there will be a couple of weeks where I will be completely unavailable. I also would only be able to mentor a subset of the mentioned tasks.

**Comment by m3nu** [comment]
Thanks! That's still very helpful.

**Comment by real-yfprojects** [comment]
> I can co-mentor, especially if the money goes to PSF or borg. However, there will be a couple of weeks where I will be completely unavailable. I also would only be able to mentor a subset of the mentioned tasks.

In that time others can do the mentoring. This is encouraged by Google. Since all communication should be made public this is also easily possible.

**Comment by ThomasWaldmann** [comment]
@m3nu Yes, you could add me as admin (but think of it rather as a fallback / backup).

**Comment by witten** [comment]
This all sounds good, and thanks for spearheading @m3nu. 

> Any regular contributor you on Borgmatic and Borg that may want to be mentors?

The main candidate that comes to mind is @grantbevis due to his excellent work on docker-borgmatic.

**Comment by m3nu** [comment]
Yes, definitely a fallback. Let's first see *how* we end up joining.

Attracting students with Docker and devops skills could be good. Would you want to be a mentor, @grantbevis and are there possible tasks? The devops part could cover [ansible-role-borgbackup](https://github.com/borgbase/ansible-role-borgbackup) and testing setup as well.

@witten, do you have any suitable tasks in mind? I'll add them above. The PSF [suggests](https://python-gsoc.org/mentors.html#orgtemplate) to have a few beginner tasks and some advanced.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg-import/ there could be some easy tasks, like importing from misc. other backup tools to borg.

**Comment by witten** [comment]
> @witten, do you have any suitable tasks in mind? I'll add them above. The PSF [suggests](https://python-gsoc.org/mentors.html#orgtemplate) to have a few beginner tasks and some advanced.

I'm going through and tagging tickets with a ["good first issue" label](https://projects.torsion.org/borgmatic-collective/borgmatic/issues?q=&type=all&state=open&labels=52&milestone=0&assignee=0&poster=0) for this. More to come there; there are a lot of open issues.

**Comment by m3nu** [comment]
Great! Linked those. Later maybe we emphasize 2-3 important ones.

**Comment by m3nu** [comment]
> https://github.com/borgbackup/borg-import/ there could be some easy tasks, like importing from misc. other backup tools to borg.

I didn't know this exists. 😄 But sure, let's put it there. It's definitely isolated and simple to test.

**Comment by real-yfprojects** [comment]
[This article](https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list.html) seems to be important for writing an ideas list that gets accepted.

>When Google Administrators review the hundreds of organization applications the primary thing >they look at is the quality of the Ideas list. An Ideas list should follow these guidelines:
>
>1. Each project on the Ideas list should include: a) a project title/description b) more >detailed description of the project (2-5 sentences) c) expected outcomes d) skills >required/preferred e) possible mentors f) expected size of project (175 or 350 hour). And if >possible, an easy, medium or hard rating of each project.
>2. Projects should take ~175 hours or ~350 hours for GSoC contributors to complete. We >understand some GSoC contributors will take less time (if they have more knowledge of the >topic or codebase) while others could spend more time. It is also possible that a given >project idea could be 175 hours or 350 hours depending on the scope of the idea. If the GSoC >contributor proposes to do a smaller scope of the idea then it might be a 175 hr project >versus if they propose doing more work with their proposal it could be a 350 hour project.
> 3. Have multiple ideas. Even if you are a new organization and only want one or two GSoC >contributors showing that you have multiple ideas (a bare minimum of 4 solid ideas) is vital. >And for an organization hoping for 4 or more GSoC contributors you should have at least 8-10 >ideas and having them categorized is a nice touch if you have subcategories of topics within >your project.
> 4. Make it easy for Administrators to find your Ideas list. When reviewing many hundreds of >organizations Program Admins can only spend a certain amount of time looking for your Ideas list. Many organizations are rejected because Program Admins couldn’t find the actual Ideas list because the URL the org gave had a bunch of other unrelated information on it and wasn’t clear where to find the actual Ideas list.
>5. Make sure to update your Project Ideas. Even if you plan to use some of the ideas that >weren’t chosen from a previous year at least put effort into changing the page to say 20XX Ideas list. It is not encouraging for Program Admins to see an outdated list. It also makes it seem like your project might be stale as you don’t have new ideas for GSoC contributors to work on if it still shows ideas from the previous year or even two years before and is marked as >such.
> 6. Never link to just a bug tracker. This is almost always an automatic rejection. Yes, really. When Admins open the issue tracker if there is an expanded description of the project with the items listed in point 1 above that is acceptable. If an org can’t take the time to create a document or a page with their Ideas List fleshed out then why would Google expect they would be willing to mentor GSoC contributors for 3+ hours a week for the next 3 months?
>7. Don’t be vague about the ideas. Be sure to write a few sentences describing what you need accomplished and not just an overall theoretical version of what you might want.
> 8.   Be sure the URL you link to for your Ideas list works. Have someone else test it as well before you submit your application. Sometimes people don’t have permissions set correctly or paste an incorrect URL which will also mean a rejection.

**Comment by m3nu** [comment]
Point taken. I've moved this to a Wiki, so everyone can add to it and it looks more permanent.

https://github.com/borgbase/vorta/wiki/Google-Summer-of-Code-2023-Ideas

**Comment by m3nu** [comment]
I've expanded on the Vorta tasks.

Maybe you also let me know the main issues you'd want to see expanded, @witten and @ThomasWaldmann. 🙏

**Comment by Hofer-Julian** [comment]
> Point taken. I've moved this to a Wiki, so everyone can add to it and it looks more permanent.
> 
> https://github.com/borgbase/vorta/wiki/Google-Summer-of-Code-2023-Ideas

This looks good!
Regarding running backups as root: I assume this would be a Linux-only feature? Might be good to clarify that. This is also the only task where I would be unsure what's the best way to implement this.

**Comment by m3nu** [comment]
Also not sure on the root thing. I think it would need some testing and catching errors on a Linux desktop.

**Comment by grantbevis** [comment]
> Yes, definitely a fallback. Let's first see _how_ we end up joining.
> 
> Attracting students with Docker and devops skills could be good. Would you want to be a mentor, @grantbevis and are there possible tasks? The devops part could cover [ansible-role-borgbackup](https://github.com/borgbase/ansible-role-borgbackup) and testing setup as well.
> 
> @witten, do you have any suitable tasks in mind? I'll add them above. The PSF [suggests](https://python-gsoc.org/mentors.html#orgtemplate) to have a few beginner tasks and some advanced.

I’d have to look into this but sure I’d love to be involved. Thank you for the mention @witten

I’m happy to mentor on any aspects of DevOps, do we need to submit workshop ideas to google? I’m currently on mobile and need to read the full information/thread still

**Comment by m3nu** [comment]
> I’m happy to mentor on any aspects of DevOps, do we need to submit workshop ideas to google? I’m currently on mobile and need to read the full information/thread still

Thanks for stepping up! Yes, it would be great if you can write up a few tasks in 2-3 sentences. Anything you deem suitable and well-defined. Could also be testing.

**Comment by m3nu** [comment]
Expanded on the more obvious Borg and Ansible tasks:

https://github.com/borgbase/vorta/wiki/Google-Summer-of-Code-2023-Ideas

**Comment by witten** [comment]
@m3nu Looks like I don't have perms to edit that wiki page..? I'm happy to expand/highlight the borgmatic issues there. Thanks.

**Comment by m3nu** [comment]
Right... Added you to the repo. Let me know if you see an edit button on the page now.

**Comment by witten** [comment]
Yup, thank you!

**Comment by grantbevis** [comment]
@m3nu / @witten - Here are some ideas for some project work for the docker portion of the borgmatic project;

- Remove antiquated msmtp and ntfy images and update documentation to reflect this

> This has been a point of confusion for users for many years and recently we started including apprise which fulfils the duty of both msmtp and ntfy in a simpler package

- Create a minimal/extended docker image setup

> A recentish request to have a minimal no-frills base image and then an extended docker image with more tools included. I think we would also include the ability to provide a variable containing a string of additional packages users would like installed. This would then be processed during entry.sh and install any additional tools users wish.

- Add CI for the docker images including linting (hadolint) and test builds as we currently only utilise CD to deploy the image to GitHub/Docker Hub registries.

> Might be worth investigating if we could run the borgmatic unit/integration tests using the docker-borgmatic image as I don't think it does currently @witten ?

Those are the the ideas I can think of off the top of my head, if I think of any more I will report back to this thread 👍🏽

**Comment by m3nu** [comment]
Happy to report that the PSF has accepted our application as sub-org. 🎉

> You are receiving this email because you applied as Borg Collective for GSoC with Python Software Foundation for GSoC 2023. You application has been reviewed and has been accepted.

Thanks to everyone here who provided input at the last minute on the day before the deadline. 😄 You can already see the "Borg Collective" on their [ideas page](https://python-gsoc.org/ideas.html).

So what happens next?

- We'll get some number of student slots assigned. This depends on the number of mentors we have and what the PSF gets from Google. Might also be less for new orgs.
- We need to get the word out to attract the best applicants. Like on Twitter, Reddit and maybe with a note on the project README. [Eligibility](https://developers.google.com/open-source/gsoc/faq#what_are_the_eligibility_requirements_for_participation) this year is not just for students, but FOSS beginners in general.
- Then applicants will submit proposals to work on specific tasks. Naturally we want to select the most qualified, suitable and motivated candidates. And also distribute them across the different projects.
- Once the actual work starts, it's important to provide guidance to contributors and keep them on track. The stipend is a decent month's salary, so the hours should be accounted for. We also want to push our projects forward and get code that can be used for a long time. The PSF has some internal tools and experience to help with this.

**Comment by m3nu** [comment]
Thanks for the tasks, @grantbevis. Already added them to the wiki. I like how @witten added hours and difficulty. We should probably add this to all major tasks and prioritize them too.

Also, @grantbevis , please share your email privately to `hello@borgbase.com`, so I can add you as mentor on the PSF site.

**Comment by grantbevis** [comment]
@m3nu, Email sent just now; Thank you!

**Comment by ThomasWaldmann** [comment]
About docker within the `borgbackup/borg` project: i do not use docker, that's why it is not in there.

The reason why platform testing uses VMs (and not docker or other containers) is that it needs to run on very different OSes: misc. linux dists, misc BSDs, openindiana. Some stuff might actually depend on kernel and OS specifics. Currently some work is being done on native win32 support, so that might come as a VM at some time also (currently just done via github CI).

**Comment by m3nu** [comment]
Yeah, I know the issue. I didn't put it as task for that reason. The Docker stuff is just for the Borgmatic image for now. QEMU may be a lighter alternative to Virtualbox at some point. Lima may make it [work](https://github.com/lima-vm/lima/issues/1096).

**Comment by real-yfprojects** [comment]
I would like to have a few sentences about our user bases: number of installs, server and desktop users

I also found [this resource from PSF](https://python-gsoc.org/mentors.html). It suggests pointing to easy bugs to try out for interested contributors. I will expand the `Getting Started` section to include those as well as some more details about the path to writing an application which I will adopt from the [PSF](https://python-gsoc.org/index.html).

**Comment by Hofer-Julian** [comment]
> I would like to have a few sentences about our user bases: number of installs, server and desktop users

Good idea.

The platform is also of importance for the students.
Vorta only works on macOS and Linux, so they would have to have a machine available with one of these operating systems if they don't want to work in a VM.
Borg also still requires a Unix-like operating system, as far as I can see.
But maybe there WSL would be enough?

**Comment by m3nu** [comment]
Doing a simple PR should be part of the application. Else we can only look at the name of the university.

Vorta in WSL is possible but I wouldn't recommend it. Maybe easier to work on the CLI repos in this case.

**Comment by real-yfprojects** [comment]
@witten We should link https://projects.torsion.org/borgmatic-collective/borgmatic instead of the github repo, don't we?

**Comment by Hofer-Julian** [comment]
> Vorta in WSL is possible but I wouldn't recommend it. Maybe easier to work on the CLI repos in this case.

Yes, it probably wasn't clear in my message, but I also was thinking about borg, borgmatic and docker when it comes to WSL.

**Comment by m3nu** [comment]
Yeah, there could be some suggested skills near the "Technologies" part to avoid any misunderstanding. Maybe good because Python is used for so many things these days.

**Comment by real-yfprojects** [comment]
We should also require potential contributors to have basic knowledge of git and the (programming) languages required.

> I also found [this resource from PSF](https://python-gsoc.org/mentors.html). It suggests pointing to easy bugs to try out for interested contributors. I will expand the `Getting Started` section to include those as well as some more details about the path to writing an application which I will adopt from the [PSF](https://python-gsoc.org/index.html).

Added that. Feel free to improve upon the paragraphs I have written.

**Comment by m3nu** [comment]
We got some feedback on our ideas page. Pretty much what we had planned to add anyways:

- [ ] add difficulty level, hours, etc for all tasks. (and remove low-prio tasks)
- [ ] move difficulty level, hours, etc to the top. So order could be: title, difficulty, skills, size/hours, description, issue link.
- [ ] about skills: we can add them. Maybe common skills at the top and then additional skills per-task.

**Comment by m3nu** [comment]
For 1., maybe we change the formatting to have like a title and bold attributes. Will be easier to read than a list and we have fewer tasks anyways.

**Comment by m3nu** [comment]
Done expanding and editing. Please have a look and feel free to expand or correct.

https://github.com/borgbase/vorta/wiki/Google-Summer-of-Code-2023-Ideas

**Comment by m3nu** [comment]
Made sure every task has 2 possible mentors, since that's a requirement. Details to be figures out, once we see the level of interest for different tasks.

**Comment by ThomasWaldmann** [comment]
About the borg task:
- borg-import: what do you thin, it could be (FOSS) backup tools in general, not just rsync-based tools (the latter are already supported, so except maybe different dir structures how they could be arranged, there is not much to do).
- more refined borg return codes: we have some detailled ticket there, but noone stepped up yet for implementing it. error return codes should be easy, warning return codes are difficult to do in a good way I guess.

**Comment by Hofer-Julian** [comment]
@real-yfprojects @m3nu made you both moderators on the matrix channel (assuming these accounts aren't imposters with very good timing)

**Comment by real-yfprojects** [comment]
> @real-yfprojects @m3nu made you both moderators on the matrix channel (assuming these accounts aren't imposters with very good timing) 

Mine isn't.

**Comment by m3nu** [comment]
You have the right guy.

Also updated the Wiki page a bit to make the application process a numbered list. So it's clearer for applicants.

We should also think about promoting the program and task ideas widely to attract the most qualified and relevant applicants. My ideas:

- [ ] Post on [Reddit r/BorgBackup](https://www.reddit.com/r/BorgBackup/)
- [ ] Add note on project's README and homepage – Will do this for Vorta.
- [ ] Official [Borg Twitter](https://twitter.com/borgbackup) (managed by @ThomasWaldmann) and BorgBase Twitter.
- [ ] Relevant blogs and newsletters - already reached out to some.
- [ ] BorgBase monthly newsletter
- [ ] In project's IRCs
- [ ] ... what else?

**Comment by Hofer-Julian** [comment]
Borgmatic [Mastodon](https://chaos.social/@borgmatic@fosstodon.org) maybe?

**Comment by ThomasWaldmann** [comment]
Before announcing something, we maybe should wait until @m3nu's org got accepted for SoC by google or until it is clear how many students we'll get from PSF (which I'ld assume will get accepted, but even that has to be seen still).

**Comment by real-yfprojects** [comment]
If I announced before Google officially accepted us, I would make it very clear that we might not get accepted in the end.

**Comment by m3nu** [comment]
Thanks for the tweaks, @real-yfprojects. We can still refine ideas, once there is interest. For now it's good to give a general idea and raise interest. More details are better of course.

The learning field would be a bonus, but the [reference PSF project](https://github.com/fury-gl/fury/wiki/Google-Summer-of-Code-2023-(GSOC2023)) didn't have it. They did have more details in the description and task outline.

🚨 Reminder @ThomasWaldmann @witten @real-yfprojects: If you haven't already, please use the PSF invite link to register an account on [blogs.python-gsoc.org](https://blogs.python-gsoc.org/). Then you'll show up as mentor with the project and get email updates.

**Comment by m3nu** [comment]
> If I announced before Google officially accepted us, I would make it very clear that we might not get accepted in the end.

The only risk is that the PSF doesn't get accepted. Not likely, I think. So OK to announce it. We can still wait of course. I was merely collecting ideas for later.

**Comment by real-yfprojects** [comment]
> Then you'll show up as mentor with the project

I got two and accepted both. However I don't see myself showing up anywhere.

**Comment by real-yfprojects** [comment]
> Do you see the sub-org [here](https://blogs.python-gsoc.org/en/suborg/application/)?

I think the web interface is a bit buggy since I can see the *suborg profiles* but I can't see the existing application. Your link leads me to a form for creating a new one.

**Comment by real-yfprojects** [comment]
I added some more vorta project ideas. 

> Regarding running backups as root: [...] This is also the only task where I would be unsure what's the best way to implement this.

I have written out this task in full anyways. Please tell me whether you think we should keep it as an idea.

**Comment by real-yfprojects** [comment]
Google employees will start reviewing applications (including project idea boards) starting on February 7[^1].

[^1]: https://developers.google.com/open-source/gsoc/timeline?hl=en

**Comment by Hofer-Julian** [comment]
> I added some more vorta project ideas.
> 
> > Regarding running backups as root: [...] This is also the only task where I would be unsure what's the best way to implement this.
> 
> I have written out this task in full anyways. Please tell me whether you think we should keep it as an idea.

It is one of the most wanted features. But it's hard to get right, and e.g. extracting as root can easily break your system. It's also a design question, how would you expose it? But if you feel you have a good idea how it should be implemented then I see no reason why you shouldn't mentor it

**Comment by Hofer-Julian** [comment]
I removed myself as mentor for this task :)

**Comment by real-yfprojects** [comment]
> But if you feel you have a good idea how it should be implemented then I see no reason why you shouldn't mentor it

I feel like doing research and figuring out the best solution is part of a medium difficulty task. Additionally the community has already done some experiments running vorta as root using sudo or polkit.

**Comment by m3nu** [comment]
I'm also not happy with the root task. But if someone brings a solid solution, why not. I just can't tell you how to do it in detail.

> I think the web interface is a bit buggy

It is. I removed you from the admin field and added you as mentor only. Maybe now making a mentor account works. I wouldn't stress about this particluar web interface, since the real action will be in the Google dashboard. They Django thing is more for internal tracking, I think. And for blog updates.

**Comment by witten** [comment]
I may have jumped the gun a little before catching up on all of these comments.. I've posted announcements on borgmatic Mastodon and IRC! I also added another borgmatic project to the ideas page, and I'm trying to register with the Python GSoC site but haven't yet received the registration email.

**Comment by m3nu** [comment]
Announcements are fine. The project is accepted.

I've just resent the email in the in their system. I think. `w**@**ion.org`

If you don't receive it, I'll email them.

**Comment by witten** [comment]
That's the email address, but still not seeing it on my end. (I checked spam folders and even the mail server log.)

**Comment by m3nu** [comment]
My test email also didn't arrive. And the first I got were delayed by a few hours.

Let's wait until tomorrow and then I'll email the guy.

**Comment by m3nu** [comment]
I've reported it in their IRC. When I registered, the email arrived as one batch a few hours later.

**Comment by m3nu** [comment]
Nice. Then only @ThomasWaldmann missing.

**Comment by real-yfprojects** [comment]
@m3nu Can you look over the time estimates for the vorta tasks? I don't know how you derived your estimates but I have a hard time with that.

**Comment by m3nu** [comment]
It's either 350 or 175 hours in total. Full or part time (mentioned [here](https://python-gsoc.org/contributors.html))

So I put it as 1, 1/2 or 1/2 project roughly. And 25 hours for the much smaller tasks.

You think it's too much or too little? I tried to be on the higher side.

Our tasks aren't big enough for a full project, so best if people choose a few. And we should aim to have full time spots, if we only get 2.

**Comment by ThomasWaldmann** [comment]
I setup my python-gsoc account now.

**Comment by real-yfprojects** [comment]
> You think it's too much or too little?

I am just very bad at estimating the time needed. So I can't tell you.

>  I tried to be on the higher side.

:+1:

**Comment by real-yfprojects** [comment]
I thought over the time estimates again. I would propose to change the time estimates for these ideas:

error wizard | 100 hours
borg live testing | 100 hours
root | 100 hours
profile sidebar | 175 hours
borg command hooks | 150 hours
search in diff and extract view | 75 hours
summary line in source view | 100 hours

**Comment by m3nu** [comment]
No arguments for or against either estimate. 😄

Multiples of 350/175 hours may make it easier to add them up to a full project.

**Comment by ThomasWaldmann** [comment]
about the "exclude GUI": shouldn't that rather be a "include/exclude patterns GUI"?

borg's `--exclude` option is a bit less powerful (it only excludes) than `--pattern` (which also knows about includes and no-recurse excludes and different pattern styles).

**Comment by m3nu** [comment]
This dialog would be about exclusions only but uses the pattern option internally IIRC. Whatever gets the job done. Similar to [this](https://github.com/borgbase/vorta/issues/907#issue-819525302) dialog in Nextcloud.

I wouldn't make it *include* files at the same time, since that may be confusing. That part is already done by the file selector and I don't recall any complaints about it. Could still be improved by combining file and folder selection (a Qt limitation).

**Comment by ThomasWaldmann** [comment]
I just added a log viewer task for vorta. Needs time estimate and mentors.

I find that is pretty essential missing feature, I missed it each time I got rc 1 or 2.

**Comment by ThomasWaldmann** [comment]
@m3nu one case it needs patterns and includes is if you want to include a path inside an excluded path.

**Comment by real-yfprojects** [comment]
The exclude GUI can later be expanded for  include rules if requested / or already by the contributor if he/she has the time.

**Comment by real-yfprojects** [comment]
> Needs time estimate and mentors.

I'll add me and @m3nu + @Hofer-Julian too.

**Comment by real-yfprojects** [comment]
I think log syntax highlighting and filtering log lines make this a medium difficulty task (or maybe medium-hard -- I am not sure).

**Comment by ThomasWaldmann** [comment]
@real-yfprojects Why do you think so? It could log the level (DEBUG/INFO/WARNING/ERROR) on each line.

**Comment by real-yfprojects** [comment]
There are still some TODOs in the idea list but I commented them out so that they can't be seen in the rich text.

I also sorted the tasks by time and in case of the same time by difficulty.

> Why do you think so? It could log the level (DEBUG/INFO/WARNING/ERROR) on each line.

I am not sure what you mean. Firstly filtering log lines by vorta session or borg command isn't that easy, i think. Secondly I would expand the task on implementing more highlighting then just colouring the line uniformly depending on the log level.

**Comment by real-yfprojects** [comment]
I just asked the PSF guys: 
**We shouldn't edit our project ideas page any more** -- besides fixing typos or other errors.

**Comment by ThomasWaldmann** [comment]
@real-yfprojects well, either each borg command needs to be introduced by some unique marker log line **if all is contained in a single log file**.

But it might be easier to just write a new log file per borg command.

And I don't think we need complex highlighting. People mainly need to easily see warnings and errors.

**Comment by real-yfprojects** [comment]
I see. We can adjust the difficulty after the review process.

**Comment by witten** [comment]
FWIW, borgmatic only colors whole log lines per log level, and sends the logs for all Borg commands to the same place (whether stdout, syslog, or a single log file). And log level filtering is supported by a verbosity flag.

**Comment by m3nu** [comment]
The org selection is now complete and I'll share more after everything is official. Likely later today or tomorrow.

**Comment by m3nu** [comment]
Org selection is now complete and the Python Foundation got accepted. See all orgs [here](https://summerofcode.withgoogle.com/programs/2023/organizations). My company wasn't, which doesn't surprise me when looking at the org list. All are heavyweights or some kind of foundations around large projects.

Thanks to everyone who helped create and improve the ideas list. It was an important part in the selection process. 🙏

Next focus should be on attracting the best students/contributors to the project. That's where the PR plan comes in. https://github.com/borgbase/vorta/issues/1575#issuecomment-1418695332. I'll try to find out when is the best time for that.

**Comment by real-yfprojects** [comment]
Now we can modify our ideas list again. So if you had any additional ideas in the last couple of weeks that you want to add or if you want to change anything else you can do that now.

For vorta I will add a new task for implementing a _getting started wizard_.

**Comment by ThomasWaldmann** [comment]
## Task: Improve modularization of vorta source

That is likely going to be one big complete merge conflict with everything else done in GSoC.

Such tasks are better done when there is low parallel activity in the project (== not in GSoC).

**Comment by m3nu** [comment]
Agreed with @ThomasWaldmann . Let's keep this for later.

**Comment by real-yfprojects** [comment]
> I'll try to find out when is the best time for that.

According to the [announcement](https://opensource.googleblog.com/2023/02/mentor-organizations-announced-for.html), this time has already begun. Google provides the [gsoc logo](https://developers.google.com/open-source/gsoc/resources/marketing) for such purposes.

**Comment by m3nu** [comment]
Time for the big PR push:

- Reddit [post](https://www.reddit.com/r/BorgBackup/comments/11ffz2v/get_paid_by_google_to_work_on_borgrelated_open/) is out
- BorgBase monthly report with a note on this is going out tomorrow
- [Twitter](https://twitter.com/borg_base/status/1631024280346476552) is out
- anything else that reaches a relevant audience quickly?

**Comment by ThomasWaldmann** [comment]
- retweeted from "borgbackup" twitter account
- same post to mastodon chaos.social
- posted reddit link to borgbackup mailing list

**Comment by witten** [comment]
- boosted and upvoted the above
- commented on https://www.reddit.com/r/csMajors/comments/11bupyg/google_summer_of_code_experience/
- commented on https://www.reddit.com/r/BITSPilani/comments/11ehbdf/what_exactly_is_gsoc/
- commented on https://www.reddit.com/r/EngineeringStudents/comments/11ehc9b/what_exactly_is_gsoc/

There might be other discussions on Reddit or other sites where we could weigh in.

**Comment by diivi** [comment]
How about an email to the python-gsoc mailing list too? [gsoc-general@python.org](mailto:gsoc-general@python.org). This might attract other python devs too.

**Comment by m3nu** [comment]
Maybe not too many beginners there though.

**Comment by real-yfprojects** [comment]
Next up would be deciding on a communication channel for applications. Looking at the [template](https://github.com/python-gsoc/python-gsoc.github.io/blob/main/ApplicationTemplate.md) there is private information that shouldn't be shared in public. So either ones uses a private communication channel or one only discusses the non-sensitive parts of the application. I think the latter is viable but should we use a github issue, discussion or something else for it?

**Comment by m3nu** [comment]
Private place will be best for this.

I can think of 2 simple ways here:
- Private room on IRC + Google Docs?
- I can throw up a Flarum forum with Github login, Markdown and private discussions.

**Comment by Hofer-Julian** [comment]
> Private room on IRC + Google Docs for comments?

I guess you use IRC for chat rooms in general?
If not then maybe something a bit friendlier that also works asynchronously (Matrix, Discord, Slack,...)

**Comment by real-yfprojects** [comment]
> If not then maybe something a bit friendlier that also works asynchronously (Matrix, Discord, Slack,...)

Three of us have Matrix already set up.

**Comment by grantbevis** [comment]
We could create a private GitHub repo and use the discussion feature with issues/projects. I’ve been working with GitHub professionally and this is the way we interact privately with GitHub themselves

**Comment by real-yfprojects** [comment]
> We could create a private GitHub repo and use the discussion feature with issues/projects. I’ve been working with GitHub professionally and this is the way we interact privately with GitHub themselves

Interesting idea. However I am not sure what the benefit would be to using Matrix (assuming you willing to create a matrix account).

**Comment by grantbevis** [comment]
No issues here just offering an idea into the hat

**Comment by real-yfprojects** [comment]
We already started with [diivi](https://github.com/diivi)'s application in a matrix room. Can you join? He is considering working on borg (@TW), vorta and borgmatic (@witten).

**Comment by real-yfprojects** [comment]
We still have to add a note to the vorta README and website. See https://github.com/borgbase/vorta/issues/1575#issuecomment-1418695332.

**Comment by m3nu** [comment]
I'll update the README.

**Comment by m3nu** [comment]
Has everyone gotten their mentor invite from Google yesterday? This is the most important part because the payouts to PSF are determined by the mentors they have in the system. If someone didn't get it, let me know and I'll raise it with them.

**Comment by Hofer-Julian** [comment]
> Has everyone gotten their mentor invite from Google yesterday? This is the most important part because the payouts to PSF are determined by the mentors they have in the system. If someone didn't get it, let me know and I'll raise it with them.

I've got it.
Still have to follow the instructions though.

**Comment by grantbevis** [comment]
> Has everyone gotten their mentor invite from Google yesterday? This is the most important part because the payouts to PSF are determined by the mentors they have in the system. If someone didn't get it, let me know and I'll raise it with them.

I’ve got it and signed up 👍🏼

**Comment by ThomasWaldmann** [comment]
Got the invite and registered.

Was a bit strange as it did not work without me using my google account although I didn't use that yet for PSF GSoC.

**Comment by witten** [comment]
I also was able to register, although I was getting errors and a blank page until I cleared my cookies for that site. Since I'm not normally a GMail user, I set up an auto-forward to my actual email account that will hopefully take care of that. TW, you may want to do the same!

**Comment by Hofer-Julian** [comment]
> I also was able to register, although I was getting errors and a blank page until I cleared my cookies for that site. Since I'm not normally a GMail user, I set up an auto-forward to my actual email account that will hopefully take care of that. TW, you may want to do the same!

Same for me.

**Comment by real-yfprojects** [comment]
> Same for me. 

It doesn't work in my Firefox at all because of some issue with cross origin referrer/scripting -- I am not sure. But I managed it in another Browser.

**Comment by real-yfprojects** [comment]
> We already started with [diivi](https://github.com/diivi)'s application in a matrix room. Can you join? He is considering working on borg (@tw), vorta and borgmatic (@witten).

?

**Comment by real-yfprojects** [comment]
Did you all receive the email google sent all mentors on 17th March?

**Comment by m3nu** [comment]
Just forwarded the same to you.

**Comment by witten** [comment]
> You do see yourself as mentor in the Google platform, @witten ?

Yup, I show up as: "Python Software Foundation (mentor)".

**Comment by ThomasWaldmann** [comment]
No.

**Comment by real-yfprojects** [comment]
> No.

So how do we go about that?

**Comment by m3nu** [comment]
Now in IRC. Closing here.
