### ISSUE TITLE
Setup ci tests with real borg versions.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1619]
Testing vorta functionalities with real borg versions would be super useful I think. Mainly as a regression test but also for supporting new borg versions.

#### Tasks

- [ ] Write a script for creating a diverse test repository + source 
- [ ] Write tests for the borg jobs and output parsing
- [ ] Setup ci (with matrix)
  - [ ] Build different borg versions
  - [ ] Run tests
